# -*- coding: utf-8 -*-
"""E-commerce sales performance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125yGDVdALpAijL1K0uCOH6DN_KCCk78T
"""



"""## Load Olist Datasets

### Subtask:
Import the pandas library and read each Olist CSV file into a separate DataFrame with a descriptive variable name.

"""

import pandas as pd
import sqlite3
from pathlib import Path

geolocation_df = pd.read_csv('olist_geolocation_dataset.csv')
product_category_translation_df = pd.read_csv('product_category_name_translation.csv')
order_items_df = pd.read_csv('olist_order_items_dataset.csv')
products_df = pd.read_csv('olist_products_dataset.csv')
customers_df = pd.read_csv('olist_customers_dataset.csv')
order_reviews_df = pd.read_csv('olist_order_reviews_dataset.csv')
order_payments_df = pd.read_csv('olist_order_payments_dataset.csv')
sellers_df = pd.read_csv('olist_sellers_dataset.csv')
orders_df = pd.read_csv('olist_orders_dataset.csv')

print("All Olist datasets loaded successfully into DataFrames.")

dataframes = {
    'geolocation_df': geolocation_df,
    'product_category_translation_df': product_category_translation_df,
    'order_items_df': order_items_df,
    'products_df': products_df,
    'customers_df': customers_df,
    'order_reviews_df': order_reviews_df,
    'order_payments_df': order_payments_df,
    'sellers_df': sellers_df,
    'orders_df': orders_df
}

def inspect_df(name, df):
    print(f"\n📊 TABLE: {name}")
    print("-" * 50)

    # Shape
    print(f"Shape: {df.shape}")

    # Columns & Types
    print("\nColumns & Data Types:")
    for col, dtype in df.dtypes.items():
        print(f"  - {col}: {dtype}")

    # Missing values
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    print("\nMissing Values:")
    if len(missing) == 0:
        print("  None")
    else:
        for col, val in missing.items():
            print(f"  - {col}: {val}")

    # Duplicates
    print(f"\nDuplicate Rows: {df.duplicated().sum()}")

    print("-" * 50)


for name, df in dataframes.items():
    inspect_df(name, df)

"""# Convert date columns before sending data to SQL"""

date_cols_orders = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_cols_orders:
    orders_df[col] = pd.to_datetime(
        orders_df[col],
        format='%d/%m/%Y %H:%M',
        errors='coerce'
    )

orders_df[date_cols_orders].dtypes
order_items_df["shipping_limit_date"].dtype

orders_df['order_purchase_timestamp'].head()
orders_df['order_purchase_timestamp'].isna().sum()

orders_df['order_purchase_timestamp'] = pd.to_datetime(
    orders_df['order_purchase_timestamp'],
    errors='coerce'
)

for col in date_cols_orders:
    print(col, orders_df[col].dtype)

orders_df['order_purchase_timestamp'].head(20)

"""# Create a SQLite database"""

conn = sqlite3.connect("ecommerce_analysis.db")

"""# Push pandas DataFrames into SQLite tables"""

orders_df.to_sql("orders", conn, if_exists="replace", index=False)
order_items_df.to_sql("order_items", conn, if_exists= "replace", index = False)
order_payments_df.to_sql("order_payments", conn, if_exists="replace", index=False)
customers_df.to_sql("customers", conn, if_exists="replace", index=False)
products_df.to_sql("products", conn, if_exists="replace" , index=False)
product_category_translation_df.to_sql("category_translation", conn, if_exists="replace", index=False)
geolocation_df.to_sql("geolocation", conn, if_exists="replace", index=False)

"""# reusable SQL query function"""

def run_query(query, conn=conn):
    return pd.read_sql_query(query, conn)

run_query("SELECT COUNT(*) AS row_count FROM orders;")
run_query("SELECT COUNT(*) AS row_count FROM order_items;")
run_query("SELECT COUNT(*) AS row_count FROM order_payments;")
run_query("SELECT COUNT(*) AS row_count FROM customers;")
run_query("SELECT COUNT(*) AS row_count FROM products;")
run_query("SELECT COUNT(*) AS row_count FROM category_translation;")

"""# Running sql magic"""

!pip install ipython-sql

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql

# Commented out IPython magic to ensure Python compatibility.
# %sql sqlite:///ecommerce_analysis.db

"""**First SQL test query: order status distribution**"""

!pip install prettytable==3.7.0

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#     order_status,
#     COUNT(*) AS order_count
# FROM orders
# GROUP BY order_status
# ORDER BY order_count DESC;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT COUNT(DISTINCT order_id) AS delivered_orders
# FROM orders
# WHERE order_status = 'delivered';

"""KPI 1"""

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT STRFTIME('%Y-%m', o.order_purchase_timestamp) AS month, \
ROUND(SUM(op.payment_value), 2) AS monthly_revenue \
FROM orders o \
JOIN order_payments op ON o.order_id = op.order_id \
WHERE o.order_status = 'delivered' \
GROUP BY month \
ORDER BY month;

result = %sql SELECT STRFTIME('%Y-%m', o.order_purchase_timestamp) AS month, \
ROUND(SUM(op.payment_value), 2) AS monthly_revenue \
FROM orders o \
JOIN order_payments op ON o.order_id = op.order_id \
WHERE o.order_status = 'delivered' \
GROUP BY month \
ORDER BY month;
dfm = result.DataFrame()

import matplotlib.pyplot as plt

dfm['month'] = pd.to_datetime(dfm['month'])

plt.figure()
plt.plot(dfm['month'], dfm['monthly_revenue'])

plt.xticks(rotation=45)
plt.title('Monthly Revenue')
plt.xlabel('Month')
plt.ylabel('Revenue')

plt.show()

"""KPI 2"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#     STRFTIME('%Y-%m', order_purchase_timestamp) AS month,
#     COUNT(*)
# FROM orders
# GROUP BY month
# ;

"""KPI3

Distinct customers
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#     COUNT(DISTINCT c.customer_unique_id) AS active_customers
# FROM orders o
# JOIN customers c
#     ON o.customer_id = c.customer_id
# WHERE o.order_status = 'delivered';

"""total orders"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#     COUNT( * ) AS Number_of_orders
# FROM orders o
# JOIN customers c
#     ON o.customer_id = c.customer_id
# WHERE o.order_status = 'delivered';

"""repeat costumers"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT COUNT(*) AS repeat_customers
# FROM (
#     SELECT
#         c.customer_unique_id,
#         COUNT(o.order_id) AS delivered_orders
#     FROM orders o
#     JOIN customers c
#         ON o.customer_id = c.customer_id
#     WHERE o.order_status = 'delivered'
#     GROUP BY c.customer_unique_id
#     HAVING COUNT(o.order_id) > 1
# );

"""customer retention"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#     COUNT(CASE WHEN delivered_orders > 1 THEN 1 END) * 100.0 / COUNT(*) AS repeat_customer_rate
# FROM (
#     SELECT
#         c.customer_unique_id,
#         COUNT(o.order_id) AS delivered_orders
#     FROM orders o
#     JOIN customers c
#         ON o.customer_id = c.customer_id
#     WHERE o.order_status = 'delivered'
#     GROUP BY c.customer_unique_id
# );

"""# Average Order Value (AOV)"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#     order_id,
#     COUNT(*) AS payment_rows
# FROM order_payments
# GROUP BY order_id
# HAVING COUNT(*) > 1
# ORDER BY payment_rows DESC;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#     ROUND(SUM(op.payment_value) / COUNT(DISTINCT o.order_id), 2) AS avg_order_value
# FROM order_payments op
# JOIN orders o
#     ON op.order_id = o.order_id
# WHERE o.order_status = 'delivered';

query_kpi_summary = """
SELECT
    ROUND(SUM(op.payment_value), 2) AS total_revenue,
    COUNT(DISTINCT o.order_id) AS total_orders,
    COUNT(DISTINCT c.customer_unique_id) AS active_customers,
    ROUND(SUM(op.payment_value) / COUNT(DISTINCT o.order_id), 2) AS avg_order_value
FROM orders o
JOIN order_payments op
    ON o.order_id = op.order_id
JOIN customers c
    ON o.customer_id = c.customer_id
WHERE o.order_status = 'delivered';
"""

kpi_summary_df = run_query(query_kpi_summary)
kpi_summary_df

query_monthly_trends = """
SELECT
    STRFTIME('%Y-%m', o.order_purchase_timestamp) AS month,
    ROUND(SUM(op.payment_value), 2) AS revenue,
    COUNT(DISTINCT o.order_id) AS orders,
    ROUND(SUM(op.payment_value) / COUNT(DISTINCT o.order_id), 2) AS avg_order_value
FROM orders o
JOIN order_payments op
    ON o.order_id = op.order_id
WHERE o.order_status = 'delivered'
GROUP BY month
ORDER BY month ;
"""

monthly_trends_df = run_query(query_monthly_trends)
monthly_trends_df

monthly_trends_df.plot(x='month', y='revenue', figsize=(12,5), title='Monthly Revenue')
monthly_trends_df.plot(x='month', y='orders', figsize=(12,5), title='Monthly Orders')
monthly_trends_df.plot(x='month', y='orders', figsize=(12,5), title='avg_order_value')

"""# Category Revenue"""

query_category_performance = """
SELECT
    COALESCE(ct.product_category_name_english, 'Unknown') AS category,
    ROUND(SUM(oi.price), 2) AS total_revenue,
    COUNT(*) AS total_items_sold
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
LEFT JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
WHERE o.order_status = 'delivered'
GROUP BY category
ORDER BY total_revenue DESC
LIMIT 20;
"""

category_df = run_query(query_category_performance)
category_df

query_order_categories = """
SELECT DISTINCT
    o.order_id,
    COALESCE(ct.product_category_name_english, 'Unknown') AS category
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
LEFT JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
WHERE o.order_status = 'delivered';
"""

order_categories_df = run_query(query_order_categories)
order_categories_df.head()

categories_per_order = (
    order_categories_df.groupby('order_id')['category']
    .nunique()
    .reset_index(name='num_categories')
)

categories_per_order['num_categories'].describe()

categories_per_order['num_categories'].value_counts().sort_index()

basket = (
    order_categories_df.assign(value=1)
    .pivot_table(
        index='order_id',
        columns='category',
        values='value',
        aggfunc='max',
        fill_value=0
    )
)

category_support = basket.mean().sort_values(ascending=False)
category_support.head(10)

!pip install mlxtend

from mlxtend.frequent_patterns import apriori, association_rules

frequent_itemsets = apriori(
    basket.astype(bool),
    min_support=0.0001,
    use_colnames=True
)

frequent_itemsets.sort_values('support', ascending=False).head(10)

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

rules = association_rules(
    frequent_itemsets,
    metric='lift',
    min_threshold=1.0
)

rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head()

rules_clean = rules.copy()

rules_clean['antecedents'] = rules_clean['antecedents'].apply(lambda x: ', '.join(sorted(list(x))))
rules_clean['consequents'] = rules_clean['consequents'].apply(lambda x: ', '.join(sorted(list(x))))

rules_clean = rules_clean[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
rules_clean = rules_clean.sort_values(by='lift', ascending=False)

rules_clean.head(15)

print(rules_clean.head(15).to_string(index=False))

"""# Average Delivery Time"""

query_delivery_time = """
SELECT
    ROUND(AVG(
        JULIANDAY(order_delivered_customer_date) -
        JULIANDAY(order_purchase_timestamp)
    ), 2) AS avg_delivery_days
FROM orders
WHERE order_status = 'delivered'
AND order_delivered_customer_date IS NOT NULL;
"""

run_query(query_delivery_time)

query_delivery_delay = """
SELECT
    ROUND(AVG(
        JULIANDAY(order_delivered_customer_date) -
        JULIANDAY(order_estimated_delivery_date)
    ), 2) AS avg_delay_days
FROM orders
WHERE order_status = 'delivered'
AND order_delivered_customer_date IS NOT NULL;
"""

run_query(query_delivery_delay)

query_seller_delay = """
SELECT
    oi.seller_id,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(AVG(
        JULIANDAY(o.order_delivered_customer_date) -
        JULIANDAY(o.order_estimated_delivery_date)
    ), 2) AS avg_delay_days
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
AND o.order_delivered_customer_date IS NOT NULL
GROUP BY oi.seller_id
HAVING total_orders >= 10
ORDER BY avg_delay_days DESC
LIMIT 10;
"""

seller_delay_df = run_query(query_seller_delay)
seller_delay_df

seller_delay_df.plot(
    x='seller_id',
    y='avg_delay_days',
    kind='bar',
    figsize=(12,5),
    title='Worst Performing Sellers by Delivery Delay'
)